Добавлено преобразование спецсимволов в html код
pastuhov/yii2-yml-catalog pull request #45
Opened 2017-05-19 14:14 UTC by execut

2017-05-19 14:20 UTC, pastuhov commented
лучше сделать escape опциональным поведением, т.к. он жрет много ресурсов и иногда база уже готова (и её не надо эскейпить)

2017-05-20 01:20 UTC, execut commented
Согласен. Нужен метод, который возвращает список необходимых для фильтрации атрибутов.

2017-06-14 08:58 UTC, execut commented
Добавил интерфейс EscapedAttributes для моделей. Если этот интерфейс реализован в модели, то фильтруются перечисленные в методе getEscapedAttributes атрибуты.

2017-06-14 12:26 UTC, pastuhov requested changes

2017-06-14 12:26 UTC, pastuhov commented on tests/models/SimpleOffer.php
> +            return 'Лазернй принтер 234234234"&><\'';
лучше добавить в фикстуру https://github.com/pastuhov/yii2-yml-catalog/blob/master/tests/data/test.xml

2017-06-14 12:26 UTC, pastuhov commented on tests/models/SimpleOffer.php
> +    public function getEscapedAttributes() {
метод хороший, но делать отдельный интерфейс для него не круто :) Может лучше сделать базовый для всех моделей, куда можно помещать общие методы, но тогда придется переделать проверку `if ($valuesModel instanceof EscapedAttributes) {` ?

2017-06-14 12:26 UTC, pastuhov commented on src/models/BaseModel.php
> +            if (in_array($attribute, $this->escapedAttributes)) {
лучше предварительно проверить $this->escapedAttributes, что он не пуст и вообще массив

2017-06-14 12:26 UTC, pastuhov commented on src/models/BaseModel.php
>      /**
лучше написать описание

2017-06-14 12:26 UTC, pastuhov commented on src/EscapedAttributes.php
> +}
пустой строки нет

2017-06-14 12:26 UTC, pastuhov commented on src/EscapedAttributes.php
> +/**
лучше без этих штормовских блоков

2017-06-14 12:47 UTC, execut commented on tests/models/SimpleOffer.php
> +    public function getEscapedAttributes() {
> Может лучше сделать базовый для всех моделей, куда можно помещать общие методы, но тогда придется переделать проверку if ($valuesModel instanceof EscapedAttributes) { ?
Всмысле делать проверку наличия метода getEscapedAttributes? Я выделил интерфейс, чтобы каждый раз не определять этот метод там, где он не нужен. То, что это не камильфо, понимаю) Но как быть тогда, чтобы не плодить такие методы во всех реализациях общего интерфейса моделей:
```php
    public function getEscapedAttributes() {
        return [];
    }
```

2017-06-14 12:58 UTC, execut commented on tests/models/SimpleOffer.php
> +            return 'Лазернй принтер 234234234"&><\'';
У меня не получилось это сделать, поскольку нужно вставить в xml то, чего яндекс как раз боится) Вот и сделал обходным путём. Сейчас поищу решение.

2017-06-14 13:03 UTC, pastuhov commented on tests/models/SimpleOffer.php
> +            return 'Лазернй принтер 234234234"&><\'';
попробуй https://ru.wikipedia.org/wiki/CDATA

2017-06-14 13:06 UTC, execut commented on tests/models/SimpleOffer.php
> +            return 'Лазернй принтер 234234234"&><\'';
Сделал

2017-06-14 13:06 UTC, execut commented on src/models/BaseModel.php
>      /**
Сделал

2017-06-14 13:06 UTC, execut commented on src/models/BaseModel.php
> +            if (in_array($attribute, $this->escapedAttributes)) {
Сделал исключение, когда указывается не правильное значение.

2017-06-14 13:06 UTC, execut commented on src/EscapedAttributes.php
> +/**
Сделал

2017-06-14 13:06 UTC, execut commented on src/EscapedAttributes.php
> +}
Сделал

2017-06-14 13:57 UTC, pastuhov commented
тесты падают, hhvm можно выключить вообще, будет все ок

2017-06-14 14:17 UTC, execut commented
Прошли

2017-06-15 05:27 UTC, pastuhov approved these changes

2017-06-15 05:28 UTC, merged