Пользовательский класс для подмены models/Category.php
pastuhov/yii2-yml-catalog pull request #46
Opened 2017-09-13 08:36 UTC by des1roer

Добавлена возможность использовать пользовательский класс для подмены стандартного класса yii2-yml-catalog/src/models/Category.php

2017-09-13 08:45 UTC, pastuhov reviewed
сдела

2017-09-13 08:45 UTC, pastuhov commented on src/YmlCatalog.php
> +            if (!empty($obj->customCategoryClass) && class_exists($obj->customCategoryClass)) {
сделай по аналогии

2017-09-13 08:45 UTC, pastuhov commented on src/YmlCatalog.php
> +            if (!empty($obj->customCategoryClass) && class_exists($obj->customCategoryClass)) {
тест?

2017-09-13 12:34 UTC, des1roer commented on src/YmlCatalog.php
> +            if (!empty($obj->customCategoryClass) && class_exists($obj->customCategoryClass)) {
Если проверять != null то все упадет, т.к. нет такого свойства в других xml

2017-09-13 12:34 UTC, des1roer commented on src/YmlCatalog.php
> +            if (!empty($obj->customCategoryClass) && class_exists($obj->customCategoryClass)) {
добавил

2017-09-13 13:02 UTC, pastuhov requested changes

2017-09-13 13:02 UTC, pastuhov commented on tests/models/SatomCategoryClass.php
> +<?php
SatomCategoryClass.php
опечатка?

2017-09-13 13:02 UTC, pastuhov commented on tests/models/SatomCategoryClass.php
> +}
нет пустой строки

2017-09-13 13:02 UTC, pastuhov commented on tests/models/SatomCategoryClass.php
> +class SatomCategoryClass extends \pastuhov\ymlcatalog\models\Category
описание класса?

2017-09-13 13:02 UTC, pastuhov commented on tests/models/CustomCategory.php
> +}
нет пустой строки

2017-09-13 13:02 UTC, pastuhov commented on src/YmlCatalog.php
> +            if (!empty($obj->customCategoryClass) && class_exists($obj->customCategoryClass)) {
почему нельзя как с offer?
$model = \Yii::createObject($this->customOfferClass);
зачем $obj->customCategoryClass?!

2017-09-13 14:25 UTC, des1roer commented on tests/models/SatomCategoryClass.php
> +<?php
Пользовательский класс как пример

2017-09-14 08:11 UTC, des1roer commented on tests/models/SatomCategoryClass.php
> +class SatomCategoryClass extends \pastuhov\ymlcatalog\models\Category
fix

2017-09-14 08:11 UTC, des1roer commented on tests/models/SatomCategoryClass.php
> +}
fix

2017-09-14 08:11 UTC, des1roer commented on tests/models/CustomCategory.php
> +}
fix

2017-09-14 08:36 UTC, pastuhov approved these changes

2017-09-14 08:36 UTC, merged