Настраиваемые длины тэгов
pastuhov/yii2-yml-catalog pull request #50
Opened 2017-11-10 12:20 UTC by des1roer

Добавлена возможность указать длину тэгов для валидации

2017-11-10 12:36 UTC, pastuhov commented
Каково снование для этого изменения?

2017-11-10 12:37 UTC, pastuhov requested changes

2017-11-10 12:37 UTC, pastuhov commented on src/models/SimpleOffer.php
> +    public static $max_length_sales_notes = 50;
тут надо бы кемелКейс таки

2017-11-11 06:55 UTC, des1roer commented
Для некоторых площадок (например Mindbox), допустимы длины тэгов, отличающиеся от стандартов  Яндекс маркета. Для удобной модификации длины введены константы

2017-11-11 08:07 UTC, pastuhov approved these changes

2017-11-11 08:07 UTC, merged